# Generated by Django 4.2.3 on 2023-07-11 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_likes_from_client_alter_likes_to_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='from_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_client', to='clients.client', verbose_name='От клиента'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='to_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_client', to='clients.client', verbose_name='К клиента'),
        ),
    ]
